-- HMS 0010: reference data. Generated from HMS_R1_Foundation_Spec.xlsx v0.4 (Roles, Permissions).
-- Re-run scratchpad/gen_seed.py if the workbook changes, then add a NEW migration for the difference. Never edit an applied one.


insert into public.currencies (code, name, decimals) values
 ('NGN','Nigerian naira',2),('USD','US dollar',2),('EUR','Euro',2),('GBP','Pound sterling',2),
 ('GHS','Ghanaian cedi',2),('KES','Kenyan shilling',2),('ZAR','South African rand',2),
 ('XOF','West African CFA franc',0),('UGX','Ugandan shilling',0),('TZS','Tanzanian shilling',2),('RWF','Rwandan franc',0)
on conflict (code) do nothing;

-- Plans are configuration (A16). Prices are left empty until Peter sets them.
insert into public.plans (code, name, max_rooms, max_properties, max_users, trial_days) values
 ('starter','Starter',20,1,10,30),
 ('standard','Standard',60,1,25,30),
 ('pro','Pro',150,3,60,30),
 ('enterprise','Enterprise',null,null,null,30)
on conflict (code) do nothing;

insert into public.country_templates (country_code, name, currency, timezone, tax_lines, payment_methods, charge_codes, verified, notes) values
 ('NG','Nigeria','NGN','Africa/Lagos','[
 {"code":"SC","name":"Service charge","rate":10,"calc_base":"net","seq":1,"applies_to":["room","fnb","other"],"verified":false},
 {"code":"VAT","name":"VAT","rate":7.5,"calc_base":"net_plus_prior","seq":2,"applies_to":["room","fnb","other"],"verified":false},
 {"code":"STATE_LEVY","name":"State hotel and consumption levy (set your state rate)","rate":0,"calc_base":"net","seq":3,"applies_to":["room","fnb"],"verified":false}
]'::jsonb,'[
 {"code":"CASH","name":"Cash","kind":"cash"},
 {"code":"POS","name":"Card (POS terminal)","kind":"card_terminal"},
 {"code":"TRANSFER","name":"Bank transfer","kind":"bank_transfer"},
 {"code":"OTHER","name":"Other","kind":"other"}
]'::jsonb,'[
 {"code":"ROOM","name":"Room charge","revenue_group":"room","taxable":true,"is_system":true},
 {"code":"FEE_CXL","name":"Cancellation fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"FEE_NOSHOW","name":"No-show fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"LAUNDRY","name":"Laundry","revenue_group":"other","taxable":true},
 {"code":"MINIBAR","name":"Minibar","revenue_group":"fnb","taxable":true},
 {"code":"RESTAURANT","name":"Restaurant","revenue_group":"fnb","taxable":true},
 {"code":"EARLY_CI","name":"Early check-in","revenue_group":"room","taxable":true},
 {"code":"LATE_CO","name":"Late check-out","revenue_group":"room","taxable":true},
 {"code":"MISC","name":"Miscellaneous","revenue_group":"other","taxable":true}
]'::jsonb,false,'VAT 7.5%, service charge 10% and state levy lines are starting values. A local accountant must confirm them before a hotel goes live (assumption A11).'),
 ('GH','Ghana','GHS','Africa/Accra','[]'::jsonb,'[
 {"code":"CASH","name":"Cash","kind":"cash"},
 {"code":"POS","name":"Card (POS terminal)","kind":"card_terminal"},
 {"code":"TRANSFER","name":"Bank transfer","kind":"bank_transfer"},
 {"code":"OTHER","name":"Other","kind":"other"}
]'::jsonb,'[
 {"code":"ROOM","name":"Room charge","revenue_group":"room","taxable":true,"is_system":true},
 {"code":"FEE_CXL","name":"Cancellation fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"FEE_NOSHOW","name":"No-show fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"LAUNDRY","name":"Laundry","revenue_group":"other","taxable":true},
 {"code":"MINIBAR","name":"Minibar","revenue_group":"fnb","taxable":true},
 {"code":"RESTAURANT","name":"Restaurant","revenue_group":"fnb","taxable":true},
 {"code":"EARLY_CI","name":"Early check-in","revenue_group":"room","taxable":true},
 {"code":"LATE_CO","name":"Late check-out","revenue_group":"room","taxable":true},
 {"code":"MISC","name":"Miscellaneous","revenue_group":"other","taxable":true}
]'::jsonb,false,'No tax lines seeded. Add the levies that apply.'),
 ('KE','Kenya','KES','Africa/Nairobi','[]'::jsonb,'[
 {"code":"CASH","name":"Cash","kind":"cash"},
 {"code":"POS","name":"Card (POS terminal)","kind":"card_terminal"},
 {"code":"TRANSFER","name":"Bank transfer","kind":"bank_transfer"},
 {"code":"OTHER","name":"Other","kind":"other"}
]'::jsonb,'[
 {"code":"ROOM","name":"Room charge","revenue_group":"room","taxable":true,"is_system":true},
 {"code":"FEE_CXL","name":"Cancellation fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"FEE_NOSHOW","name":"No-show fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"LAUNDRY","name":"Laundry","revenue_group":"other","taxable":true},
 {"code":"MINIBAR","name":"Minibar","revenue_group":"fnb","taxable":true},
 {"code":"RESTAURANT","name":"Restaurant","revenue_group":"fnb","taxable":true},
 {"code":"EARLY_CI","name":"Early check-in","revenue_group":"room","taxable":true},
 {"code":"LATE_CO","name":"Late check-out","revenue_group":"room","taxable":true},
 {"code":"MISC","name":"Miscellaneous","revenue_group":"other","taxable":true}
]'::jsonb,false,'No tax lines seeded. Add the levies that apply.'),
 ('ZA','South Africa','ZAR','Africa/Johannesburg','[]'::jsonb,'[
 {"code":"CASH","name":"Cash","kind":"cash"},
 {"code":"POS","name":"Card (POS terminal)","kind":"card_terminal"},
 {"code":"TRANSFER","name":"Bank transfer","kind":"bank_transfer"},
 {"code":"OTHER","name":"Other","kind":"other"}
]'::jsonb,'[
 {"code":"ROOM","name":"Room charge","revenue_group":"room","taxable":true,"is_system":true},
 {"code":"FEE_CXL","name":"Cancellation fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"FEE_NOSHOW","name":"No-show fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"LAUNDRY","name":"Laundry","revenue_group":"other","taxable":true},
 {"code":"MINIBAR","name":"Minibar","revenue_group":"fnb","taxable":true},
 {"code":"RESTAURANT","name":"Restaurant","revenue_group":"fnb","taxable":true},
 {"code":"EARLY_CI","name":"Early check-in","revenue_group":"room","taxable":true},
 {"code":"LATE_CO","name":"Late check-out","revenue_group":"room","taxable":true},
 {"code":"MISC","name":"Miscellaneous","revenue_group":"other","taxable":true}
]'::jsonb,false,'No tax lines seeded. Add the levies that apply.'),
 ('ZZ','Generic (any other country)','USD','UTC','[]'::jsonb,'[
 {"code":"CASH","name":"Cash","kind":"cash"},
 {"code":"POS","name":"Card (POS terminal)","kind":"card_terminal"},
 {"code":"TRANSFER","name":"Bank transfer","kind":"bank_transfer"},
 {"code":"OTHER","name":"Other","kind":"other"}
]'::jsonb,'[
 {"code":"ROOM","name":"Room charge","revenue_group":"room","taxable":true,"is_system":true},
 {"code":"FEE_CXL","name":"Cancellation fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"FEE_NOSHOW","name":"No-show fee","revenue_group":"fee","taxable":false,"is_system":true},
 {"code":"LAUNDRY","name":"Laundry","revenue_group":"other","taxable":true},
 {"code":"MINIBAR","name":"Minibar","revenue_group":"fnb","taxable":true},
 {"code":"RESTAURANT","name":"Restaurant","revenue_group":"fnb","taxable":true},
 {"code":"EARLY_CI","name":"Early check-in","revenue_group":"room","taxable":true},
 {"code":"LATE_CO","name":"Late check-out","revenue_group":"room","taxable":true},
 {"code":"MISC","name":"Miscellaneous","revenue_group":"other","taxable":true}
]'::jsonb,false,'Fallback template. Set currency, timezone and taxes for the property.')
on conflict (country_code) do nothing;

insert into public.permissions (key, module, release, description, sensitive) values
 ('platform.tenant.manage','PLT','R1','Create, configure, suspend tenants; provision first tenant admin',true),
 ('platform.plan.manage','PLT','R1','Manage subscription plans and limits',true),
 ('platform.support.access','PLT','R1','Break-glass access into a tenant (time-boxed, reason, tenant notified)',true),
 ('platform.audit.view','PLT','R1','View platform-level audit log',false),
 ('platform.billing.manage','PLT','R1','Activate, extend or invoice a tenant manually; issue credits',true),
 ('org.subscription.manage','M15','R1','View plan and usage; change plan; cancel subscription',true),
 ('org.billing.paymentmethod','M15','R1b','Manage subscription payment method and view invoices',false),
 ('org.property.create','M02','R1','Create additional properties inside a tenant',true),
 ('dash.view_exec','M01','R1','View executive dashboard (KPIs, revenue)',false),
 ('dash.view_ops','M01','R1','View operations dashboard (arrivals, departures, readiness, queues)',false),
 ('setup.view','M02','R1','View property configuration (room types, rates, taxes)',false),
 ('setup.property.manage','M02','R1','Create/edit property profile, timezone, currency',true),
 ('setup.roomtype.manage','M02','R1','Create/edit room types',false),
 ('setup.room.manage','M02','R1','Create/edit physical rooms, buildings, floors',false),
 ('setup.rateplan.manage','M02','R1','Create/edit rate plans, restrictions, cancellation rules',true),
 ('setup.tax.manage','M02','R1','Create/edit taxes and service charges',true),
 ('setup.fx.manage','M02','R1','Enter daily exchange rates',false),
 ('setup.policy.manage','M02','R1','Manage departments, outlets, policies, readiness rules',false),
 ('res.availability.view','M03','R1','Search availability and view reservation calendar',false),
 ('res.view','M03','R1','View reservations',false),
 ('res.create','M03','R1','Create reservations',false),
 ('res.edit','M03','R1','Modify reservations (reprices where applicable)',false),
 ('res.cancel','M03','R1','Cancel reservation',true),
 ('res.noshow.mark','M03','R1','Mark reservation as no-show manually',true),
 ('res.reinstate','M03','R1','Reinstate a cancelled or no-show reservation',true),
 ('res.rate.override','M03','R1','Override the rate plan price',true),
 ('res.group.manage','M03','R1','Create and manage group bookings and rooming lists',false),
 ('res.deposit.request','M03','R1','Set deposit or guarantee requirement on a reservation',false),
 ('fo.board.view','M04','R1','View front desk board',false),
 ('fo.checkin','M04','R1','Check in a reservation',false),
 ('fo.checkin.walkin','M04','R1','Create and check in a walk-in',false),
 ('fo.checkout','M04','R1','Check out a guest (folio must be settled)',false),
 ('fo.checkout.unsettled.approve','M04','R1','Approve checkout with an open balance',true),
 ('fo.checkout.reverse','M04','R1','Undo a checkout on the same business date',true),
 ('fo.room.assign','M04','R1','Assign or reassign a room before arrival',false),
 ('fo.roommove','M04','R1','Move a guest to another room',false),
 ('fo.roommove.complimentary','M04','R1','Move or upgrade with no price change',true),
 ('fo.stay.extend','M04','R1','Extend or shorten a stay',false),
 ('svc.request.create','M04','R1','Log a guest service request',false),
 ('svc.request.manage','M04','R1','Assign, progress and complete service requests',false),
 ('guest.view','M05','R1','View guest profile and history',false),
 ('guest.create','M05','R1','Create guest profile',false),
 ('guest.edit','M05','R1','Edit guest profile',false),
 ('guest.idocs.view','M05','R1','View identity document details',true),
 ('guest.merge','M05','R1','Merge duplicate guest profiles',true),
 ('guest.complaint.manage','M05','R1','Record and resolve complaints and feedback',false),
 ('room.view','M06','R1','View room board and room detail',false),
 ('room.status.update','M06','R1','Change room condition through allowed transitions',false),
 ('room.status.override','M06','R1','Force a room condition outside allowed transitions',true),
 ('room.block.request','M06','R1','Request an Out of Order / Out of Service block',false),
 ('room.block.approve','M06','R1','Approve or reject a room block',true),
 ('room.block.release','M06','R1','Release an active block',false),
 ('hk.board.view','M07','R1','View housekeeping board',false),
 ('hk.task.assign','M07','R1','Create and assign cleaning tasks',false),
 ('hk.task.execute','M07','R1','Start and complete cleaning tasks',false),
 ('hk.inspect','M07','R1','Inspect rooms; pass or fail',false),
 ('hk.lostfound.manage','M07','R1','Log and release lost and found items',false),
 ('mnt.view','M08','R1','View maintenance board and tickets',false),
 ('mnt.ticket.create','M08','R1','Report an issue / create ticket',false),
 ('mnt.ticket.manage','M08','R1','Prioritise, assign and reopen tickets',false),
 ('mnt.ticket.work','M08','R1','Work and resolve tickets',false),
 ('mnt.ticket.close','M08','R1','Verify and close resolved tickets',false),
 ('mnt.ticket.cancel','M08','R1','Cancel invalid or duplicate ticket',true),
 ('fin.folio.view','M12','R1','View folios',false),
 ('fin.charge.post','M12','R1','Post a charge',false),
 ('fin.payment.post','M12','R1','Post a payment',false),
 ('fin.deposit.take','M12','R1','Take a deposit',false),
 ('fin.discount.apply','M12','R1','Apply a discount (limit-based)',true),
 ('fin.discount.approve','M12','R1','Approve discounts above limit',true),
 ('fin.adjust.post','M12','R1','Initiate an adjustment',true),
 ('fin.adjust.approve','M12','R1','Approve an adjustment',true),
 ('fin.reverse.post','M12','R1','Initiate a reversal of a posted transaction',true),
 ('fin.refund.post','M12','R1','Initiate a refund',true),
 ('fin.refund.approve','M12','R1','Approve a refund',true),
 ('fin.folio.transfer','M12','R1','Transfer transactions between folios',true),
 ('fin.folio.split','M12','R1','Create additional folio for a stay',false),
 ('fin.folio.reopen','M12','R1','Reopen a closed folio',true),
 ('fin.invoice.issue','M12','R1','Issue invoice or receipt',false),
 ('audit.businessdate.view','M12','R1','View current business date and audit status',false),
 ('audit.night.run','M12','R2','Run night audit',true),
 ('audit.night.override','M12','R2','Close night audit with unresolved exceptions',true),
 ('fin.shift.manage','M12','R2','Open and close own cashier shift',false),
 ('fin.shift.reconcile','M12','R2','Reconcile shifts and approve variance',true),
 ('sales.company.manage','M13','R2','Create/edit company accounts and negotiated rate links',false),
 ('sales.credit.approve','M13','R2','Approve credit terms / direct bill',true),
 ('sales.pipeline.manage','M13','R2','Manage leads and pipeline',false),
 ('sales.event.manage','M13','R2','Manage events and venues',false),
 ('pos.order.manage','M09','R2','Create and settle POS orders',false),
 ('pos.roomcharge','M09','R2','Post POS order to a room folio',false),
 ('pos.discount','M09','R2','Apply POS discount',true),
 ('pos.kitchen.update','M09','R2','Update order status on kitchen display',false),
 ('inv.view','M10','R2','View stock',false),
 ('inv.move','M10','R2','Receive, issue, transfer, adjust, count stock',true),
 ('inv.count.approve','M10','R2','Approve stock count variance',true),
 ('proc.request.create','M11','R2','Raise a purchase request',false),
 ('proc.request.approve','M11','R2','Approve a purchase request',true),
 ('proc.po.create','M11','R2','Create a purchase order',false),
 ('proc.po.approve','M11','R2','Approve a purchase order',true),
 ('proc.receive','M11','R2','Record goods receipt',false),
 ('hr.employee.manage','M14','R2','Manage employee records',false),
 ('hr.roster.manage','M14','R2','Manage rosters and shifts',false),
 ('adm.user.manage','M15','R1','Create, edit, disable users and set property scope',true),
 ('adm.role.manage','M15','R1','Create and edit roles and permission sets',true),
 ('adm.role.assign','M15','R1','Assign roles to users',true),
 ('adm.audit.view','M15','R1','View audit log',false),
 ('adm.config.manage','M15','R1','Manage notifications and system configuration',false),
 ('data.export','M15','R1','Bulk data export',true),
 ('rep.ops.view','M16','R1','View operations reports',false),
 ('rep.fin.view','M16','R1','View financial reports',false),
 ('rep.mgmt.view','M16','R2','View management analytics',false),
 ('rep.export','M16','R1','Export reports',true),
 ('portal.self','M17','R3','Guest self-service on own records',false)
on conflict (key) do nothing;

insert into public.roles (tenant_id, code, name, description, first_release, is_system)
select null, v.code, v.name, v.description, v.rel, true from (values
 ('PSA','Platform Super Admin','Runs the SaaS platform: creates tenants (hotel organisations), plans, suspends tenants, platform audit. No access to any tenant''s guest, room or financial data. Break-glass support access is time-boxed, audited and notifies the tenant.','R1'),
 ('SYS','System Administrator','Tenant administrator. Configuration, users, roles, audit view, creates properties when assigned at tenant scope. No operational or financial posting rights.','R1'),
 ('OWN','Hotel Owner / Investor','Read-only management view. Added: the earlier matrix had no row for A01.','R1'),
 ('GM','General Manager','Oversight and top-level approvals and overrides. Not a data-entry role.','R1'),
 ('FOM','Front Office Manager','Front office supervisor with first-level approvals. Added: BRD names these owners but no role existed.','R1'),
 ('FDO','Front Desk Officer','Arrivals, departures, check-in/out, folio entry within limits.','R1'),
 ('RSV','Reservation Officer','Availability, bookings, amendments, deposit requests.','R1'),
 ('REV','Revenue Manager','Rate plans and rate overrides. Added: SET-04 named a Revenue user with no role.','R1'),
 ('HKS','Housekeeping Supervisor','Assign, inspect, release rooms.','R1'),
 ('ATT','Room Attendant','Mobile task execution only.','R1'),
 ('MNT','Maintenance Officer','Tickets, work, block requests.','R1'),
 ('CSH','Cashier','Payments and folio postings.','R1'),
 ('NAU','Night Auditor','Runs night audit from R2. Added: FIN-03 named Finance/GM only, which is not workable overnight.','R2'),
 ('ACC','Accountant / Finance','Financial control, approvals, reopen, reconciliation.','R1'),
 ('SLS','Sales Manager','Company accounts, credit and pipeline in R2. In R1 can create and edit reservations.','R2'),
 ('EVT','Event Manager','Events and group billing.','R2'),
 ('HRA','HR / Administrator','Employee records. Creates user records but does not assign roles.','R2'),
 ('FNB','F&B Staff','Orders and room charges.','R2'),
 ('KIT','Kitchen Staff','Kitchen display.','R2'),
 ('PRC','Procurement Officer','Creates POs. Cannot approve them.','R2'),
 ('STK','Storekeeper','Stock movements and receipts.','R2'),
 ('DEP','Department Head','Raises and approves department purchase requests. Added: PROC-01 named ''Department'' with no role.','R2'),
 ('GST','Guest','Self-service portal.','R3')
) as v(code, name, description, rel)
where not exists (select 1 from public.roles r where r.tenant_id is null and r.code = v.code);

insert into public.role_permissions (role_id, permission_key, grant_level)
select r.id, v.k, v.lvl from (values
 ('PSA','platform.tenant.manage','Y'),
 ('PSA','platform.plan.manage','Y'),
 ('PSA','platform.support.access','Y'),
 ('PSA','platform.audit.view','Y'),
 ('PSA','platform.billing.manage','Y'),
 ('SYS','org.subscription.manage','Y'),
 ('SYS','org.billing.paymentmethod','Y'),
 ('SYS','org.property.create','Y'),
 ('SYS','setup.view','Y'),
 ('SYS','setup.property.manage','Y'),
 ('SYS','setup.roomtype.manage','Y'),
 ('SYS','setup.room.manage','Y'),
 ('SYS','setup.rateplan.manage','Y'),
 ('SYS','setup.tax.manage','Y'),
 ('SYS','setup.fx.manage','Y'),
 ('SYS','setup.policy.manage','Y'),
 ('SYS','adm.user.manage','Y'),
 ('SYS','adm.role.manage','Y'),
 ('SYS','adm.role.assign','Y'),
 ('SYS','adm.audit.view','Y'),
 ('SYS','adm.config.manage','Y'),
 ('SYS','data.export','Y'),
 ('OWN','dash.view_exec','Y'),
 ('OWN','rep.ops.view','Y'),
 ('OWN','rep.fin.view','Y'),
 ('OWN','rep.mgmt.view','Y'),
 ('OWN','rep.export','Y'),
 ('GM','dash.view_exec','Y'),
 ('GM','dash.view_ops','Y'),
 ('GM','setup.view','Y'),
 ('GM','res.availability.view','Y'),
 ('GM','res.view','Y'),
 ('GM','res.cancel','Y'),
 ('GM','res.reinstate','Y'),
 ('GM','res.rate.override','Y'),
 ('GM','fo.board.view','Y'),
 ('GM','fo.checkout.unsettled.approve','Y'),
 ('GM','guest.view','Y'),
 ('GM','room.view','Y'),
 ('GM','room.block.approve','Y'),
 ('GM','hk.board.view','Y'),
 ('GM','mnt.view','Y'),
 ('GM','fin.folio.view','Y'),
 ('GM','fin.discount.approve','Y'),
 ('GM','fin.adjust.approve','Y'),
 ('GM','fin.refund.approve','Y'),
 ('GM','audit.businessdate.view','Y'),
 ('GM','audit.night.override','Y'),
 ('GM','sales.credit.approve','Y'),
 ('GM','proc.request.approve','Y'),
 ('GM','proc.po.approve','Y'),
 ('GM','adm.audit.view','Y'),
 ('GM','data.export','Y'),
 ('GM','rep.ops.view','Y'),
 ('GM','rep.fin.view','Y'),
 ('GM','rep.mgmt.view','Y'),
 ('GM','rep.export','Y'),
 ('FOM','dash.view_exec','Y'),
 ('FOM','dash.view_ops','Y'),
 ('FOM','setup.view','Y'),
 ('FOM','setup.fx.manage','Y'),
 ('FOM','res.availability.view','Y'),
 ('FOM','res.view','Y'),
 ('FOM','res.create','Y'),
 ('FOM','res.edit','Y'),
 ('FOM','res.cancel','Y'),
 ('FOM','res.noshow.mark','Y'),
 ('FOM','res.reinstate','Y'),
 ('FOM','res.rate.override','Y'),
 ('FOM','res.group.manage','Y'),
 ('FOM','res.deposit.request','Y'),
 ('FOM','fo.board.view','Y'),
 ('FOM','fo.checkin','Y'),
 ('FOM','fo.checkin.walkin','Y'),
 ('FOM','fo.checkout','Y'),
 ('FOM','fo.checkout.unsettled.approve','L'),
 ('FOM','fo.checkout.reverse','Y'),
 ('FOM','fo.room.assign','Y'),
 ('FOM','fo.roommove','Y'),
 ('FOM','fo.roommove.complimentary','Y'),
 ('FOM','fo.stay.extend','Y'),
 ('FOM','svc.request.create','Y'),
 ('FOM','svc.request.manage','Y'),
 ('FOM','guest.view','Y'),
 ('FOM','guest.create','Y'),
 ('FOM','guest.edit','Y'),
 ('FOM','guest.idocs.view','Y'),
 ('FOM','guest.merge','Y'),
 ('FOM','guest.complaint.manage','Y'),
 ('FOM','room.view','Y'),
 ('FOM','room.status.update','Y'),
 ('FOM','room.status.override','Y'),
 ('FOM','room.block.request','Y'),
 ('FOM','room.block.approve','Y'),
 ('FOM','room.block.release','Y'),
 ('FOM','hk.board.view','Y'),
 ('FOM','mnt.view','Y'),
 ('FOM','mnt.ticket.create','Y'),
 ('FOM','fin.folio.view','Y'),
 ('FOM','fin.charge.post','Y'),
 ('FOM','fin.payment.post','Y'),
 ('FOM','fin.deposit.take','Y'),
 ('FOM','fin.discount.apply','Y'),
 ('FOM','fin.discount.approve','L'),
 ('FOM','fin.adjust.post','Y'),
 ('FOM','fin.adjust.approve','L'),
 ('FOM','fin.reverse.post','Y'),
 ('FOM','fin.refund.post','Y'),
 ('FOM','fin.refund.approve','L'),
 ('FOM','fin.folio.transfer','Y'),
 ('FOM','fin.folio.split','Y'),
 ('FOM','fin.invoice.issue','Y'),
 ('FOM','audit.businessdate.view','Y'),
 ('FOM','rep.ops.view','Y'),
 ('FOM','rep.export','Y'),
 ('FDO','dash.view_ops','Y'),
 ('FDO','setup.view','Y'),
 ('FDO','res.availability.view','Y'),
 ('FDO','res.view','Y'),
 ('FDO','res.create','Y'),
 ('FDO','res.edit','Y'),
 ('FDO','res.cancel','Y'),
 ('FDO','res.noshow.mark','Y'),
 ('FDO','res.deposit.request','Y'),
 ('FDO','fo.board.view','Y'),
 ('FDO','fo.checkin','Y'),
 ('FDO','fo.checkin.walkin','Y'),
 ('FDO','fo.checkout','Y'),
 ('FDO','fo.room.assign','Y'),
 ('FDO','fo.roommove','Y'),
 ('FDO','fo.stay.extend','Y'),
 ('FDO','svc.request.create','Y'),
 ('FDO','svc.request.manage','Y'),
 ('FDO','guest.view','Y'),
 ('FDO','guest.create','Y'),
 ('FDO','guest.edit','Y'),
 ('FDO','guest.idocs.view','Y'),
 ('FDO','guest.complaint.manage','Y'),
 ('FDO','room.view','Y'),
 ('FDO','room.block.request','Y'),
 ('FDO','mnt.ticket.create','Y'),
 ('FDO','fin.folio.view','Y'),
 ('FDO','fin.charge.post','Y'),
 ('FDO','fin.payment.post','Y'),
 ('FDO','fin.deposit.take','Y'),
 ('FDO','fin.discount.apply','L'),
 ('FDO','fin.adjust.post','Y'),
 ('FDO','fin.reverse.post','Y'),
 ('FDO','fin.folio.split','Y'),
 ('FDO','fin.invoice.issue','Y'),
 ('FDO','audit.businessdate.view','Y'),
 ('FDO','rep.ops.view','Y'),
 ('RSV','setup.view','Y'),
 ('RSV','res.availability.view','Y'),
 ('RSV','res.view','Y'),
 ('RSV','res.create','Y'),
 ('RSV','res.edit','Y'),
 ('RSV','res.cancel','Y'),
 ('RSV','res.group.manage','Y'),
 ('RSV','res.deposit.request','Y'),
 ('RSV','guest.view','Y'),
 ('RSV','guest.create','Y'),
 ('RSV','guest.edit','Y'),
 ('RSV','room.view','Y'),
 ('RSV','fin.folio.view','O'),
 ('RSV','fin.deposit.take','Y'),
 ('REV','dash.view_exec','Y'),
 ('REV','setup.view','Y'),
 ('REV','setup.rateplan.manage','Y'),
 ('REV','res.availability.view','Y'),
 ('REV','res.view','Y'),
 ('REV','res.rate.override','Y'),
 ('REV','rep.ops.view','Y'),
 ('REV','rep.fin.view','Y'),
 ('REV','rep.mgmt.view','Y'),
 ('REV','rep.export','Y'),
 ('HKS','dash.view_ops','Y'),
 ('HKS','svc.request.manage','Y'),
 ('HKS','room.view','Y'),
 ('HKS','room.status.update','Y'),
 ('HKS','room.block.request','Y'),
 ('HKS','hk.board.view','Y'),
 ('HKS','hk.task.assign','Y'),
 ('HKS','hk.task.execute','Y'),
 ('HKS','hk.inspect','Y'),
 ('HKS','hk.lostfound.manage','Y'),
 ('HKS','mnt.view','Y'),
 ('HKS','mnt.ticket.create','Y'),
 ('HKS','mnt.ticket.close','Y'),
 ('HKS','rep.ops.view','Y'),
 ('ATT','svc.request.manage','O'),
 ('ATT','room.view','O'),
 ('ATT','hk.task.execute','O'),
 ('ATT','mnt.ticket.create','Y'),
 ('MNT','svc.request.manage','O'),
 ('MNT','room.view','Y'),
 ('MNT','room.block.request','Y'),
 ('MNT','room.block.release','Y'),
 ('MNT','mnt.view','Y'),
 ('MNT','mnt.ticket.create','Y'),
 ('MNT','mnt.ticket.manage','Y'),
 ('MNT','mnt.ticket.work','Y'),
 ('MNT','mnt.ticket.close','Y'),
 ('MNT','mnt.ticket.cancel','Y'),
 ('CSH','fin.folio.view','Y'),
 ('CSH','fin.charge.post','Y'),
 ('CSH','fin.payment.post','Y'),
 ('CSH','fin.deposit.take','Y'),
 ('CSH','fin.adjust.post','Y'),
 ('CSH','fin.reverse.post','Y'),
 ('CSH','fin.refund.post','Y'),
 ('CSH','fin.invoice.issue','Y'),
 ('CSH','audit.businessdate.view','Y'),
 ('CSH','fin.shift.manage','Y'),
 ('NAU','dash.view_ops','Y'),
 ('NAU','res.noshow.mark','Y'),
 ('NAU','fo.board.view','Y'),
 ('NAU','room.view','Y'),
 ('NAU','fin.folio.view','Y'),
 ('NAU','fin.charge.post','Y'),
 ('NAU','fin.adjust.post','Y'),
 ('NAU','audit.businessdate.view','Y'),
 ('NAU','audit.night.run','Y'),
 ('NAU','rep.ops.view','Y'),
 ('NAU','rep.fin.view','Y'),
 ('ACC','dash.view_exec','Y'),
 ('ACC','setup.view','Y'),
 ('ACC','setup.tax.manage','Y'),
 ('ACC','setup.fx.manage','Y'),
 ('ACC','fo.checkout.unsettled.approve','Y'),
 ('ACC','fin.folio.view','Y'),
 ('ACC','fin.discount.approve','Y'),
 ('ACC','fin.adjust.post','Y'),
 ('ACC','fin.adjust.approve','Y'),
 ('ACC','fin.reverse.post','Y'),
 ('ACC','fin.refund.post','Y'),
 ('ACC','fin.refund.approve','Y'),
 ('ACC','fin.folio.transfer','Y'),
 ('ACC','fin.folio.reopen','Y'),
 ('ACC','fin.invoice.issue','Y'),
 ('ACC','audit.businessdate.view','Y'),
 ('ACC','audit.night.run','Y'),
 ('ACC','audit.night.override','Y'),
 ('ACC','fin.shift.reconcile','Y'),
 ('ACC','sales.credit.approve','Y'),
 ('ACC','inv.count.approve','Y'),
 ('ACC','proc.po.approve','Y'),
 ('ACC','adm.audit.view','Y'),
 ('ACC','rep.ops.view','Y'),
 ('ACC','rep.fin.view','Y'),
 ('ACC','rep.mgmt.view','Y'),
 ('ACC','rep.export','Y'),
 ('SLS','setup.view','Y'),
 ('SLS','res.availability.view','Y'),
 ('SLS','res.view','Y'),
 ('SLS','res.create','Y'),
 ('SLS','res.edit','Y'),
 ('SLS','res.cancel','Y'),
 ('SLS','res.group.manage','Y'),
 ('SLS','guest.view','Y'),
 ('SLS','guest.create','Y'),
 ('SLS','guest.edit','Y'),
 ('SLS','sales.company.manage','Y'),
 ('SLS','sales.pipeline.manage','Y'),
 ('SLS','rep.ops.view','Y'),
 ('SLS','rep.mgmt.view','Y'),
 ('EVT','setup.view','Y'),
 ('EVT','res.availability.view','Y'),
 ('EVT','res.view','Y'),
 ('EVT','res.create','Y'),
 ('EVT','res.edit','Y'),
 ('EVT','res.group.manage','Y'),
 ('EVT','room.view','Y'),
 ('EVT','fin.folio.view','O'),
 ('EVT','sales.event.manage','Y'),
 ('HRA','hr.employee.manage','Y'),
 ('HRA','hr.roster.manage','Y'),
 ('HRA','adm.user.manage','Y'),
 ('FNB','pos.order.manage','Y'),
 ('FNB','pos.roomcharge','Y'),
 ('FNB','pos.discount','L'),
 ('KIT','pos.kitchen.update','Y'),
 ('PRC','inv.view','Y'),
 ('PRC','proc.request.create','Y'),
 ('PRC','proc.po.create','Y'),
 ('STK','inv.view','Y'),
 ('STK','inv.move','Y'),
 ('STK','proc.receive','Y'),
 ('DEP','inv.view','Y'),
 ('DEP','proc.request.create','Y'),
 ('DEP','proc.request.approve','L'),
 ('GST','portal.self','O')
) as v(role, k, lvl)
join public.roles r on r.tenant_id is null and r.code = v.role
on conflict do nothing;
